name: Deploy Production

on:
  push:
    tags:
      - "*"

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          command_timeout: 180m
          script: |
            cd /data/dify
            git fetch --tags
            git checkout ${{ github.ref_name }}
            cd docker && DOCKER_BUILDKIT=1 docker compose up -d --build
